apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: bookstore
  labels:
    app: catalog-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
        tier: backend
    spec:
      containers:
      - name: catalog-service
        image: 284333427150.dkr.ecr.us-east-1.amazonaws.com/online-bookstore/catalog-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: db-password
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: aws-region
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5