apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
  namespace: bookstore
  labels:
    app: chatbot-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-service
  template:
    metadata:
      labels:
        app: chatbot-service
        tier: backend
    spec:
      serviceAccountName: chatbot-service-sa
      containers:
      - name: chatbot-service
        image: 284333427150.dkr.ecr.us-east-1.amazonaws.com/online-bookstore/chatbot-service:latest
        ports:
        - containerPort: 3006
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3006"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: aws-region
        - name: BEDROCK_MODEL_ID
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: bedrock-model-id
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5