---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: bookstore
  labels:
    app: cart-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: cart-service
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: bookstore
  labels:
    app: chatbot-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
    name: http
  selector:
    app: chatbot-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: bookstore
  labels:
    app: order-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: bookstore
  labels:
    app: payment-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bookstore
  labels:
    app: user-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app: user-service