apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: bookstore
  labels:
    app: catalog-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: catalog-service